// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySavings.ApiService.Data;

#nullable disable

namespace MySavings.ApiService.Migrations
{
    [DbContext(typeof(MySavingsDbContext))]
    [Migration("20260819163156_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MySavings.ApiService.Models.AllocationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SavingsAccountId")
                        .IsUnique();

                    b.ToTable("AllocationRules");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SecurityBuffer")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(500m);

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.MonthlyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Expenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Savings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1SavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Expenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Savings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2SavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousMonthPerson1Percent")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousMonthPerson2Percent")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSavings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique();

                    b.ToTable("MonthlyEntries");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocationSharePercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0.5m);

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("SavingsAccounts");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SavingsAccountId");

                    b.HasIndex("MonthlyEntryId", "SavingsAccountId")
                        .IsUnique();

                    b.ToTable("SavingsAllocations");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.TransferGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransferGroups");
                });

            modelBuilder.Entity("SavingsAccountTransferGroup", b =>
                {
                    b.Property<int>("SavingsAccountsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferGroupsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SavingsAccountsId", "TransferGroupsId");

                    b.HasIndex("TransferGroupsId");

                    b.ToTable("TransferGroupSavingsAccount", (string)null);
                });

            modelBuilder.Entity("MySavings.ApiService.Models.AllocationRule", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.SavingsAccount", "SavingsAccount")
                        .WithOne("AllocationRule")
                        .HasForeignKey("MySavings.ApiService.Models.AllocationRule", "SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAccount", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.Owner", null)
                        .WithMany("SavingsAccounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAllocation", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.MonthlyEntry", "MonthlyEntry")
                        .WithMany("SavingsAllocations")
                        .HasForeignKey("MonthlyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySavings.ApiService.Models.SavingsAccount", "SavingsAccount")
                        .WithMany()
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlyEntry");

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("SavingsAccountTransferGroup", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.SavingsAccount", null)
                        .WithMany()
                        .HasForeignKey("SavingsAccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySavings.ApiService.Models.TransferGroup", null)
                        .WithMany()
                        .HasForeignKey("TransferGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MySavings.ApiService.Models.MonthlyEntry", b =>
                {
                    b.Navigation("SavingsAllocations");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.Owner", b =>
                {
                    b.Navigation("SavingsAccounts");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAccount", b =>
                {
                    b.Navigation("AllocationRule");
                });
#pragma warning restore 612, 618
        }
    }
}
