// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySavings.ApiService.Data;

#nullable disable

namespace MySavings.ApiService.Migrations
{
    [DbContext(typeof(MySavingsDbContext))]
    [Migration("20260806092850_SeedDefaultPersonSettings")]
    partial class SeedDefaultPersonSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MySavings.ApiService.Models.AllocationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SavingsAccountId")
                        .IsUnique();

                    b.ToTable("AllocationRules");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.MonthlyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Expenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1Savings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person1SavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Expenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2Savings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Person2SavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousMonthPerson1Percent")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousMonthPerson2Percent")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSavings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSavingsRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique();

                    b.ToTable("MonthlyEntries");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.PersonSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonKey")
                        .IsUnique();

                    b.ToTable("PersonSettings");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SavingsAccounts");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SavingsAccountId");

                    b.HasIndex("MonthlyEntryId", "SavingsAccountId")
                        .IsUnique();

                    b.ToTable("SavingsAllocations");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.TransferGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransferGroups");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.TransferGroupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransferGroupId");

                    b.ToTable("TransferGroupItems");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.AllocationRule", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.SavingsAccount", "SavingsAccount")
                        .WithOne("AllocationRule")
                        .HasForeignKey("MySavings.ApiService.Models.AllocationRule", "SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAllocation", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.MonthlyEntry", "MonthlyEntry")
                        .WithMany("SavingsAllocations")
                        .HasForeignKey("MonthlyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySavings.ApiService.Models.SavingsAccount", "SavingsAccount")
                        .WithMany()
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlyEntry");

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.TransferGroupItem", b =>
                {
                    b.HasOne("MySavings.ApiService.Models.TransferGroup", "TransferGroup")
                        .WithMany("Items")
                        .HasForeignKey("TransferGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransferGroup");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.MonthlyEntry", b =>
                {
                    b.Navigation("SavingsAllocations");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.SavingsAccount", b =>
                {
                    b.Navigation("AllocationRule");
                });

            modelBuilder.Entity("MySavings.ApiService.Models.TransferGroup", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
